# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'siege' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for siege

  target 'siegeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'siegeUITests' do
    # Pods for testing
  end
  pod 'Firebase'

end
